name: Angular

on:
  push:
    branches: [ "main" ]

jobs:
  Vision-website:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/html/ports/Vision
    steps:  
     - name: stash
       run: git stash
     - name: pull code      
       run: git pull origin main
     - name: Install Dependencies
       run: npm install -f
     - name: create build
       run: ng build
     - name: copy htaccess
       run: cp /var/www/html/ports/Vision/.htaccess /var/www/html/ports/Vision/dist/vision-vivante
